import fs from "fs";

/**
 * Reads the data set generated by the `generate-dataset.ts` script
 *
 * Used to prepare an example array of inputs that can be used to showcase
 * different solutions.
 */
export function readInputDataSet(): number[] {
  return JSON.parse(fs.readFileSync("./dataset.json").toString());
}
